name: Push lib to nuget

env:
  working-directory:  ./dotnet-6  
  working-directory-root: ./ 

on:
  push:
    tags:
      - 'v6.[0-9]+.[0-9]+'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master 

    - name: Setup .NET      
      uses: actions/setup-dotnet@v3
      with:
       dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore
      working-directory: ${{env.working-directory}}    

    - name: Build
      run: dotnet build --no-restore
      working-directory: ${{env.working-directory}}
  
  test:
    name: Unit Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master 

    - name: Setup .NET      
      uses: actions/setup-dotnet@v3
      with:
       dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore
      working-directory: ${{env.working-directory}} 

    - name: Build
      run: dotnet build --no-restore
      working-directory: ${{env.working-directory}}

    - name: Unit Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ${{env.working-directory}}

  
  publish:
    name: Publish on nugget       
    runs-on: ubuntu-latest
    needs: 
      - build
      - test
    steps:  
     - name: Checkout
       uses: actions/checkout@master 

     - name: application directory
       run: ls -R
       working-directory: ${{env.worker-directory}}/src/bin  
